name: build container and push

on:
  push:
    branches: [ main ]
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      

