name: build container and push

on:
  push:
    branches: [ main ]
      
jobs:
  container_build:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER_NAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Containerfile
          push: true
          tags: quay.io/wzzrd/email_validation_github:latest
  upload_spec:
    name: Upload spec to RapidAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-rapidapi/create_or_update_rapidapi@master
        with:
          spec_path: openapi.json
          x_rapidapi_key: ${{ secrets.X_RAPIDAPI_KEY }}
          x_rapidapi_host: ${{ secrets.X_RAPIDAPI_HOST }}
          






