name: Linting & formatting

on:
  push:
    branches:
      - main

jobs:
  combo:
    name: Clippy + rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          command: clippy
          args: -- -D warnings

  spec_validation:
    name: verify_spec
    runs-on: ubuntu-latest
    steps:
      - name: Verify OpenAPI Spec File
        uses: eveoh/oas3-lint@v1
        with:
          spec: openapi.json
          token: ${{ secrets.GITHUB_TOKEN }}

