name: build container and push

on:
  push:
    branches: [ main ]
      
jobs:
  debug_build:
    name: Email validator build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build

  container_build:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER_NAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Containerfile
          push: true
          tags: wzzrd/email_validation_github:latest






